.travis.yml
=> Add travis continuous build.

README.md
=> Add travis-ci build badge.

naptime-models/src/main/scala/org/coursera/naptime/model/KeyFormat.scala, project/NamedDependencies.scala
=> Add `UUID` support to `KeyFormat`

naptime-pegasus/src/main/java/org/coursera/pegasus/TypedDefinitionCodec.java, naptime-pegasus/src/main/java/org/coursera/pegasus/TypedDefinitionDataCoercer.java, project/NaptimeBuild.scala, project/Sonatype.scala, project/plugins.sbt
We would like to publish artifacts to maven central for ease of consumption by
others.
=> Configure maven central publishing.

naptime-models/build.sbt, naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestTypedDefinition.courier, naptime-models/src/test/scala/org/coursera/naptime/courier/CourierAssertions.scala, naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFiltersTest.scala, naptime-models/src/test/scala/org/coursera/naptime/courier/CourierSerializerTest.scala, naptime-models/src/test/scala/org/coursera/naptime/courier/CourierTestFixtures.scala, naptime-models/src/test/scala/org/coursera/naptime/courier/SchemaInferenceTest.scala, naptime-models/src/test/scala/org/coursera/naptime/courier/TypedDefinitionsTest.scala
A number of tests were forgotten in the move over to OSS. This adds them back.
=> Move more tests over to OSS.

naptime-sbt-plugin/build.sbt, naptime-sbt-plugin/scripted.sbt, naptime-sbt-plugin/src/main/scala/org/coursera/naptime/sbt/CommentRenderer.scala, naptime-sbt-plugin/src/main/scala/org/coursera/naptime/sbt/NaptimePlugin.scala, naptime-sbt-plugin/src/main/scala/org/coursera/naptime/sbt/ScalaLibraryLocator.scala, naptime-sbt-plugin/src/main/scala/org/coursera/naptime/sbt/ScaladocExtractor.scala, naptime-sbt-plugin/src/main/scala/org/coursera/naptime/sbt/ScaladocSerializer.scala, naptime-sbt-plugin/src/main/scala/org/coursera/naptime/sbt/StringEscaper.scala, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/README.md, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/build.sbt, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/project/plugins.sbt, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/src/main/pegasus/org/coursera/example/User.courier, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/src/main/resources/application.conf, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/src/main/resources/logback.xml, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/src/main/resources/routes, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/src/main/scala/Module.scala, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/src/main/scala/resources/UserResource.scala, naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/test, project/NaptimeBuild.scala
Migrate over @yifan-coursera 's sbt plugin that extracts Scaladocs from Naptime
resources and stores them in a managed JAR resource so they can be exposed to
the API explorer project.
In the process, I've (1) migrated to using an AutoPlugin, and (2) added a test.
=> Add scaladoc extractor sbt plugin.

version.sbt
Changes include:
- Add sbt plugin to extract Scaladocs for resources.
- Add attributes to Resource courier models
- Move more tests over from closed source to open source.
Internal / infrastructure changes:
- Add travis-ci + build badge
- Cache travis-ci downloads
=> Version bump to 0.0.3

project/NaptimeBuild.scala, version.sbt
Major changes
- Adds NoRestrictions authenticator.
- Remove unnecessary plugin repository.
=> Release version 0.0.4.

gettingstarted/access.md
Add documentation regarding how to use access control in Naptime.
=> Document access control.

naptime-models/src/test/scala/org/coursera/naptime/model/KeyFormatTest.scala
Migrating over some test code related to the KeyFormats.
=> Add KeyFormatTests to oss models.

naptime/src/main/scala/org/coursera/naptime/router2/AttributesProvider.scala, naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
Note: unfortunately, due to limitations in our build system, we cannot test the
sbt plugin and this code.
=> Add extracted scaladocs to schemas

version.sbt
Key Change:
- Right-bias the `eitherOf` access control combinator.
=> Release new Naptime Version.

naptime/src/test/scala/org/coursera/naptime/access/HeaderAccessControlCombinersTest.scala
This new test uses multiple HeaderAccessControl's in a single unified test to
ensure they all compose properly.
=> Add a sophisticated auth test

gettingstarted/access.md
This commit also adds documentation on the combinators available for
`StructuredAccessControl`.
=> Reformat auth FAQ for easier link-ability.

version.sbt
Big news: Since 0.0.9, Coursera is running 100% on the released Naptime JARs.
In celebration of this, we're bumping up to 0.1.0.
Since 0.0.9, we've had a few changes:
- Streamlined helpers means less mix-in's and repetition of `def Rest = ...`
- Changed asymmetric type computation messaging from error to warnings.
- Fixed some bugs in the 2nd generation engines implementations.
- Augment Resource.courier to include a merged type (Breaking Change!!!)
- We now use reflection to infer type schemas for non-Courier types.
- Migrate over more tests from Coursera to here.
- Write some sophisticated authentication tests to ensure correctness of the
combinators.
=> Release version 0.1.0

naptime/src/main/scala/org/coursera/naptime/actions/util/DataMapUtils.scala, naptime/src/test/pegasus/org/coursera/naptime/actions/CmlContent.courier, naptime/src/test/pegasus/org/coursera/naptime/actions/CmlContentType.courier, naptime/src/test/pegasus/org/coursera/naptime/actions/CourseQnA.courier, naptime/src/test/pegasus/org/coursera/naptime/actions/ExpandedCourse.courier, naptime/src/test/pegasus/org/coursera/naptime/actions/TranslatableString.courier, naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala, version.sbt
Nested unions inside lists inside datamaps would sometimes remain
in immutable form. This commit adds a reproducing test case, and
then additionally fixes the bug.
=> Engine2 Fix: Successfully reproduced & fixed bug

naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala, version.sbt
Due to a race condition and global mutable state, the pretty
printing appears to be broken in pegasus. We therefore remove
the ability to pretty print, and that appears to fix the
problems.
=> Remove pretty printing.

naptime/src/main/scala/org/coursera/naptime/ETag.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala, naptime/src/main/scala/org/coursera/naptime/response.scala, naptime/src/test/scala/org/coursera/naptime/ETagTest.scala, naptime/src/test/scala/org/coursera/naptime/actionCategoriesTests.scala, naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala, version.sbt
=> Define strong and weak ETags separately

naptime/src/main/scala/org/coursera/naptime/ari/graphql/GraphQL.scala, naptime/src/main/scala/org/coursera/naptime/ari/models.scala, naptime/src/main/scala/org/coursera/naptime/ari/package.scala
Define key abstractions that will form the basis for the automatic
resource inclusion and GraphQL work.
=> Proposal automatic resource inclusion abstractions

version.sbt
Changes included:
- Relax Engine2 type restriction for Actions
- Fix flaky tests
- Add BadGateway as an error option
- Add If-None-Match tests for Engine2's
=> Release version 0.2.1

naptime/src/main/scala/org/coursera/naptime/access/HeaderAccessControl.scala, naptime/src/main/scala/org/coursera/naptime/access/combiner/SuccessfulOf.scala, naptime/src/test/scala/org/coursera/naptime/access/HeaderAccessControlCombinersTest.scala, version.sbt
=> Add `successfulOf` combinator to `HeaderAccessControl`

naptime/src/main/scala/org/coursera/naptime/actions/NaptimeActionSerializer.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
Support Option's as possible responses in Naptime Actions.
=> Support Option[T]'s in Action responses.

version.sbt
Changes:
- Support `Option[T]`s in NaptimeActionSerializers.
- Add `successfulOf[T](...)` to `HeaderAccessControl`.
=> Release version 0.2.2

version.sbt
Changes:
- Further relax the restrictions on what can be returned in Naptime `Actions`.
=> Release version 0.2.3.

naptime-testing/src/main/scala/org/coursera/naptime/router2/ResourceInjectionTest.scala, naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestAction.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala, naptime/src/main/scala/org/coursera/naptime/ari/fetcher/LocalFetcher.scala, naptime/src/main/scala/org/coursera/naptime/ari/models.scala, naptime/src/main/scala/org/coursera/naptime/router2/NaptimePlayRouter.scala, naptime/src/test/scala/org/coursera/naptime/actionCategoriesTests.scala, naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala, naptime/src/test/scala/org/coursera/naptime/router2/NaptimePlayRouterTest.scala
Implement the initial version of a local fetcher which an engine can
use to execute requests against local naptime resources.
=> Initial local fetcher implementation.

naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala, naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
Add a test to verify the engine correctly handles joining multiple
resources on to a top level resource.
Additionally, this commit reorganizes all the TODOs into a single list
in the EngineImplTest class.
=> Add multi-join test.

version.sbt
Fixes:
- Incorporate related resource information in resource schemas.
- Use fully-qualified reference to Keyed to fix potentail compile errors as
a result of macro invocation.
=> Release a new version of naptime.

examples/src/main/scala/controllers/GraphQlController.scala, naptime/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlContext.scala, naptime/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala, naptime/src/main/scala/schema/ResourceCompanion.scala
PTAL @saeta. This just cleans a few things up and adds some documentation, so I'm less ashamed of the code.
=> Clean up some code

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
This handles a few more edge cases around things being null or having previously unsupported types.
PTAL @saeta
=> Handle more edge cases in schema generation

naptime/src/main/scala/org/coursera/naptime/actions/NaptimeSerializer.scala
Currently, when a null field is encountered by the serializer, the exception
thrown gives no details as to what field was actually null.
We convert it to a RuntimeException, because java.lang.NPE doesn't include
a 2-arg constructor allowing an underlying exception to be passed through.
=> Wrap the NPE thrown by DataMap to include info.

version.sbt
Release new version of naptime that includes macro fixes &
more helpful error messages when encountering NPE's when
interacting with DataMaps.
=> Release Naptime version 0.2.7

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphqlSchemaProvider.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlContext.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/DefaultGraphqlSchemaProviderTest.scala, naptime-testing/src/main/scala/org/coursera/naptime/actions/RestActionTester.scala, naptime/src/main/scala/org/coursera/naptime/actions/NaptimeActionSerializer.scala, naptime/src/main/scala/org/coursera/naptime/actions/util/DataMapUtils.scala, naptime/src/main/scala/org/coursera/naptime/ari/LocalSchemaProvider.scala, naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala, naptime/src/main/scala/org/coursera/naptime/ari/fetcher/LocalFetcher.scala, naptime/src/main/scala/org/coursera/naptime/ari/models.scala, naptime/src/main/scala/org/coursera/naptime/ari/package.scala, naptime/src/main/scala/schema/ResourceCompanion.scala
Additionally, this commit refactors a few things to make supporting
a constantly changing underlying naptime schema easier to support.
=> Include GraphQL Play controller in OSS Naptime.

naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
ARI local mode should include top-level pagination information.
=> Add response pagination to ARI Local Mode.

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala, version.sbt
=> Add variables into query execution

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/graphqlParser.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParserTest.scala, naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala, naptime/src/main/scala/org/coursera/naptime/ari/fetcher/LocalFetcher.scala, version.sbt
Also fixes a few query parameter problems with the LocalFetcher and a bug with a 404 on gets in the Engine2
PTAL @saeta
=> Add support for variables in GraphQL

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphqlSchemaProvider.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala, version.sbt
PTAL @saeta .
0.3.11 currently doesn't generate schemas correctly for our production apis :(
=> Handle NullDataSchemas and log error for unknown field types

build.sbt, naptime-graphql/build.sbt, naptime-models/build.sbt, naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala, naptime-models/src/main/scala/org/coursera/naptime/courier/SchemaInference.scala, naptime-models/src/main/scala/org/coursera/naptime/courier/StringKeyCodec.scala, naptime-models/src/main/scala/org/coursera/naptime/model/KeyFormat.scala, naptime-pegasus/build.sbt, naptime-testing/build.sbt, naptime/build.sbt, naptime/src/main/scala/org/coursera/naptime/models.scala, naptime/src/main/scala/org/coursera/naptime/router2/NaptimePlayRouter.scala
Reviewers: seata
CC:
Test Plan: no warnings anymore
Auditors:
=> add flags to treat warnings as errors

examples/src/main/scala/resources/CoursesResource.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationField.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/DefaultGraphqlSchemaProviderTest.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationFieldTest.scala, version.sbt
- Adds a Pagination field on both top-level resource handlers (finders, getAlls, multiGets), as well as for inner related resources
- Bumps version up to 0.4.0
PTAL @saeta . working on tests now, but initial thoughts would be nice. (also want to make sure that this isn't blocking anyone)
=> Add fields for pagination

examples/src/main/pegasus/org/coursera/example/Course.courier, examples/src/main/scala/stores/CourseStore.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/PrimitiveFieldTest.scala
=> Fix for optional fields being null

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumField.scala
Minor fix for field names on enumfields.
PTAL @yifan-coursera
=> Fix bug with field names for enum fields

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala, version.sbt
Self explanatory. Must've been from the refactor.
PTAL @yifan-coursera
=> Fix bug with variables in query execution

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/EngineMetricsFilter.scala
=> Fix a typo and prevent double-nesting of batched responses

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumField.scala
PTAL @yifan-coursera or @jnwng  (sorry 😞)
=> Fix naming bug with enumField inside unionField

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
i.e. a Membership -> Course should still expose the `showHidden` parameter on the courses.v1 multiget
PTAL @yifan-coursera and @jnwng
=> Pull in arguments from multiget on singular related field

examples/src/main/pegasus/org/coursera/example/Course.courier, examples/src/main/scala/resources/CoursesResource.scala, examples/src/main/scala/stores/CourseStore.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala, naptime/src/main/pegasus/org/coursera/naptime/schema/ReverseRelationAnnotation.courier, naptime/src/main/scala/org/coursera/naptime/Types.scala, naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineHelpers.scala, naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala, naptime/src/main/scala/org/coursera/naptime/models.scala, version.sbt
- Converts multiget relations to be forward relations
- Adds a single-element finder relation
- Adds a get relation
- Optimize query batching for gets and multigets
=> Update reverse relation behavior

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
=> Stop throwing errors when handlers cannot be generated

naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
=> Encode that CourierCollectionResource is top-level

naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumFieldTest.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionFieldTest.scala, project/NamedDependencies.scala, version.sbt
=> Bump ScalaTest to v3.0.1

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionField.scala
The logic for handling typedDefinition unions was in the field that was built for a union. However, in cases where unions with typedDefinitions were subtypes inside a list, the logic in the field resolver was never being run.
This change extracts the typedDefinition logic to the `typeOf` method on the union and the resolver on the subfield in the union, to ensure that typedDefinition unions work inside lists too.
PTAL @vishalkuo 
cc @kchen-coursera
=> Move logic for resolving typedDefinition unions

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala, naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationField.scala, naptime-models/src/main/scala/org/coursera/naptime/courier/CourierUtils.scala, naptime-models/src/main/scala/org/coursera/naptime/model/KeyFormat.scala, naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala, naptime/src/main/scala/org/coursera/naptime/RequestEvidence.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestAction.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionBuilder.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine.scala, naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala, naptime/src/main/scala/org/coursera/naptime/path/ParsedPathKey.scala, naptime/src/main/scala/org/coursera/naptime/router2/CollectionResourceRouter.scala, naptime/src/test/scala/org/coursera/naptime/ETagTest.scala, naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
Reviewers: yifan, bryan
CC:
Test Plan: unit test
Auditors:
=> Make small fixes on various complition warnings in Naptime

naptime/src/main/scala/org/coursera/naptime/errors.scala
Add a helper function to pass Courier Model Exception Details to NaptimeActionException.  
Changes in ClientException changes https://phabricator.dkandu.me/D62549 @bryan-coursera
=> Add withExceptionDetails to NaptimeActionException

build.sbt, naptime-testing/build.sbt, project/NamedDependencies.scala, project/NaptimeBuild.scala, project/plugins.sbt, version.sbt
Reviewers:
CC:
Test Plan:
Auditors:
=> Add scala 2.12 support in naptime

naptime/src/main/scala/org/coursera/naptime/RequestEvidence.scala, naptime/src/main/scala/org/coursera/naptime/models.scala
Since there is no plan to move away from play.
=> Remove RequestEvidence required

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeTopLevelResourceField.scala, version.sbt
=> Dedup args when constructing GET handler from multiget

naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceUtils.scala, naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceUtilsTest.scala, naptime/src/main/scala/org/coursera/naptime/ari/engine/Utilities.scala
Sorry, found these issues while testing. I haven't released `0.9.2-alpha3` yet so not bumping up the version. I'll merge these changes in after doing more testing locally.
=> Use Try to be safe to NPEs, and no-op when id interpolation did not find an id

naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
=> allow public access to jsObjectToRecord

naptime/src/main/scala/org/coursera/naptime/ari/engine/Utilities.scala, version.sbt
=> Fix interpolating into nested ids which requires the original DataMap to be kept using passthroughEnabled flag

build.sbt, naptime/src/main/scala/org/coursera/naptime/models.scala, project/NaptimeBuild.scala, project/plugins.sbt, version.sbt
Play 2.6.24 doesn't fully bring in the patch that we need. More work was done which ended up in play 2.6.25: https://github.com/playframework/playframework/commit/9c32bd56ca33aa96c703b41f313b3369e74d8cec
=> Bump play version to Play 2.6.25

version.sbt
This PR bumps the version to prepare for a release. I tested this in a service and it works great.
=> Increment version from 0.11.3 → 0.11.4
