- project/NaptimeBuild.scala
- project/plugins.sbt
The courier-sbt-plugin has not been published for 2.0.1. Instead, add the
courier sbt plugin via the coursera bintray repository.
> Use courier version 2.0.2 + add coursera bintray repository.

- .gitignore
- _config.yml
- gettingstarted/index.md
Coursera internally has a quickstart guide. This has been cleaned up,
inaccuracies fixed, and included in this commit.
In order to get the code to format properly, I've added some additional
lines to the configuration file.
I've additionally added some extra lines to the `.gitignore` file to make
switching between code branches and the `gh-pages` branch a little less
cumbersome.
> Migrate the quickstart guide to gh-pages.

- naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala
- project/NamedDependencies.scala
As part of the migration for Coursera to depend on the published versions of
courscala and Naptime, I caught a test that we had forgotten to move across.
So here it is!
> Move tests from internal to oss

- naptime/src/main/pegasus/org/coursera/naptime/schema/JsValue.courier
- naptime/src/main/pegasus/org/coursera/naptime/schema/Resource.courier
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
Documentation is represented as an attribute. This commit adds in the forgotten
field to the courier models.
> Add attributes to Resources.

- project/NaptimeBuild.scala
Whenever running the `test` command in the `root` sbt project, it would run all
the tests, but then hang forever in the interactive console. This commit removes
the unnecessary configuration call. Now, you can run `test` in the root project,
and you won't have to kill your sbt shell afterwards. :-)
> Fix `test` in `root` project.

- naptime/src/main/scala/org/coursera/naptime/access/authenticator/Authenticator.scala
- naptime/src/main/scala/org/coursera/naptime/access/authenticator/combiner/NoRestrictions.scala
In order to provide a default authentication in a number of places in the codebase,
we add a NoRestrictions authenticator that allows all requests to pass.
> Add a NoRestrictions authenticator.

- project/plugins.sbt
The courier sbt plugin is now mirrored in the standard sbt plugin bintray
distribution, so we can remove our own resolver.
Note: in this commit, we comment out the travis-ci caching, in order to
properly test that this change is safe.
> Remove unused bintray repository.

- project/NaptimeBuild.scala
- project/plugins.sbt
I've added the sbt-header plugin to ensure licenses are atop all files. Note,
however, that it doesn't correctly add headers to *.sbt files, *.courier files,
or files inside sbt-test directories. There are open tickets on sbt-header for
this, so we will wait and see.
> Add sbt-header plugin to check for licenses

- naptime-models/src/main/scala/org/coursera/naptime/model/KeyFormat.scala
- version.sbt
When migrating KeyFormats it's very helpful to be able to maintain the ability
to read the old key format, while simultaneously reading & writing the new
format.
> Add withFallbackReads to KeyFormat

- naptime-testing/src/main/scala/org/coursera/naptime/actions/RestActionTester.scala
- naptime/src/main/scala/org/coursera/naptime/access/HeaderAccessControl.scala
- naptime/src/main/scala/org/coursera/naptime/access/StructuredAccessControl.scala
- naptime/src/main/scala/org/coursera/naptime/access/combiner/And.scala
- naptime/src/main/scala/org/coursera/naptime/access/combiner/AnyOf.scala
- naptime/src/main/scala/org/coursera/naptime/access/combiner/EitherOf.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- version.sbt
When testing Naptime endpoints, it's often a good idea to test the access
control mechanisms as well. Because Naptime tests operate at a higher level,
it doesn't make sense to include the parsing & decorating. It does, however,
make sense to run the Authorizors.
In order to do this while simultaneously supporting the combinators, we add a
new method to `HeaderAccessControl` called `check` that will run the Authorizer.
The type signature of `check` is a little funny in order to support the behavior
of some of the more sophisticated combinators (i.e. `anyOf`) which must support
filtering of the parsed values.
> Add testing capabilities to HeaderAccessControl

- naptime-models/src/main/scala/org/coursera/naptime/courier/SchemaInference.scala
- naptime-models/src/test/scala/org/coursera/naptime/courier/SchemaInferenceTest.scala
Previously, `SchemaInference.inferSchema` would break on schemas that included `None.type`. This change handles `None.type` correctly. 
When evaluating the following code:
```
import org.coursera.naptime.courier.SchemaInference
import scala.reflect.runtime.universe
case class WithNone(nothing: None.type)
SchemaInference.inferSchema(universe.typeOf[WithNone])
```
Before:
```
java.lang.ClassCastException: scala.reflect.internal.Types$UniqueSingleType cannot be cast to scala.reflect.api.Types$TypeRefApi
at org.coursera.naptime.courier.ScalaClassTraverser.org$coursera$naptime$courier$ScalaClassTraverser$$inferSchema(SchemaInference.scala:118)
```
After:
```
res0: play.api.libs.json.JsObject = {"name":"WithNone","type":"record","fields":[{"name":"nothing","type":"null"}],"namespace":"$line5"} …
```
> Treat None.type specially

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
When encountering a non-Courier type, run SchemaInference on the type to infer the schema if possible. If errors result, fall back to returning no schema.
> Use type inference for non-Courier types

- naptime/src/test/scala/org/coursera/naptime/FieldsTest.scala
- naptime/src/test/scala/org/coursera/naptime/JsonUtilitiesTest.scala
- naptime/src/test/scala/org/coursera/naptime/ResourceNameTest.scala
- naptime/src/test/scala/org/coursera/naptime/RestContextTest.scala
As part of removing the internal copy of naptime from Coursera's source tree,
I discovered these tests had gotten forgotten.
> Migrate over internal model tests to OSS

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NonNestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/router2/PlayNaptimeRouterIntegrationTest.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/main/scala/org/coursera/naptime/resources/resources.scala
- naptime/src/test/scala/org/coursera/naptime/actionCategoriesTests.scala
- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
- naptime/src/test/scala/org/coursera/naptime/router2/NestingCollectionResourceRouterTest.scala
As part of migrating over tests, I ended up streamlining the trait hierarchy for
Naptime. In short, I have removed the `FieldsBuilder` helper, and I've also
removed the `RestActionHelpers`, and just incorporated them into the main trait
hierarchy, as it pretty much makes no sense without them. (Internally to
Coursera, we have sub-traits that unify everything. This change is an effective
no-op for general user-land code that uses these child-traits, but will make it
much simpler to use naptime productively elsewhere, including in Naptime's own
tests!)
> Streamline helpers & migrate more test

- naptime/src/main/scala/org/coursera/naptime/Types.scala
Since the these methods still return valid values even if errors occurred, errors should be logged as warnings rather than errors.
> Change asymmetric type computation log message from error to warning

- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/main/scala/org/coursera/naptime/utilities.scala
- naptime/src/test/scala/org/coursera/naptime/actionCategoriesTests.scala
- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
- naptime/src/test/scala/org/coursera/naptime/actions/util/Validators.scala
In order to ensure a smooth migration to the 2nd-generation engines,
I've fleshed out a more sophisticated test suite that ensures that
the new engines behave appropriately.
> RestEngine2's: Carefully test resources

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/Resource.courier
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
As part of the asymmetric models approach we've adopted, we compute a
merged type that is composed of the union of the fields between the
key and the value. Sometimes, however, it's important to see the
unadulterated value type. For this, we now expose both the valueType
and the mergedType. Previously, the exposed bodyType was the mergedType,
and the valueType was not exposed at all. Hopefully with this rename,
we've also settled on good names for these types.
> Augment Resource.courier to include mergedType

- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
Add some tests to verify correct ETag behavior for the
Engine2 implementations.
> Add tests for ETag construction.

- naptime/src/main/scala/org/coursera/naptime/actions/NaptimeSerializer.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/main/scala/org/coursera/naptime/actions/util/DataMapUtils.scala
- naptime/src/test/pegasus/org/coursera/naptime/actions/CoursePlatform.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/Domain.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/DomainId.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/ExpandedCourse.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/Slug.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/SubDomainId.courier
- naptime/src/test/scala/org/coursera/naptime/actions/DomainId.scala
- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
- naptime/src/test/scala/org/coursera/naptime/actions/Slug.scala
- naptime/src/test/scala/org/coursera/naptime/actions/SubDomainId.scala
- naptime/src/test/scala/org/coursera/naptime/actions/util/DataMapUtilsTests.scala
- version.sbt
We encountered an exception in production @ Coursera regarding
a problem with immutable components of the data maps. Because we
do deep processing, we need to ensure that everything is mutable.
This commit recursively checks the tree and ensures that it is
mutable.
Exception found in production @ Coursera:
java.lang.UnsupportedOperationException: Cannot mutate a read-only map
at com.linkedin.data.collections.CheckedMap.checkMutability(CheckedMap.java:298) ~[com.linkedin.pegasus.data-3.1.1.jar:na]
at com.linkedin.data.collections.CheckedMap.clear(CheckedMap.java:158) ~[com.linkedin.pegasus.data-3.1.1.jar:na]
at org.coursera.pegasus.TypedDefinitionHandler.convertFromPegasus(TypedDefinitionHandler.java:69) ~[org.coursera.naptime.naptime-pegasus-0.1.0.jar:0.1.0]
at …
> Bugfix: Ensure datamap & contents are mutable.

- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/test/pegasus/org/coursera/naptime/actions/ExpandedCourse.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/Instructor.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/InstructorId.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/Partner.courier
- naptime/src/test/pegasus/org/coursera/naptime/actions/PartnerId.courier
- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
- version.sbt
If a request to resource A requests included resource B, and related to B
also includes resource C, we need to include the lists for A, B, and C.
Previously we only included the "first-hop" related includes. Now, we
include all transitively included related resources.
This bug was discovered in the production rollout of Engine2's. I was
able to reproduce it with a unit test case, implemented the fix, and
confirmed the new test case passes.
> Engine2: Don't elide multi-hop includes.

- naptime/src/test/scala/org/coursera/naptime/actionCategoriesTests.scala
It appears as if we regularly see timeouts when running asynchronous
tests in travis-ci. In order to make it more reliable, we should
scale the timeouts a bit.
> Make flaky test more reliable.

- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
The new engine2 implementation had a bug in serialization
when serializing facets. This commit fixes the bug, and
adds a unit test to ensure there are no regressions in the
future.
> [Engine2] Serialize Facets Correctly

- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
A requester can request to include the links metadata
which will provide some information about how the
relations relate to each other.
> [Engine2] Add links for metaprogramming.

- naptime/src/main/scala/org/coursera/naptime/ETag.scala
- naptime/src/test/scala/org/coursera/naptime/ETagTest.scala
- version.sbt
@saeta 
I've marked them as deprecated already because they're not actually correct to use and we should remove them as soon as we fix the few existing APIs.
> Add strong ETags for backwards-compatibility

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NonNestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/router2/PlayNaptimeRouterIntegrationTest.scala
- naptime/src/main/scala/org/coursera/naptime/actions/NaptimeSerializer.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/test/scala/org/coursera/naptime/actionCategoriesTests.scala
- naptime/src/test/scala/org/coursera/naptime/router2/NestingCollectionResourceRouterTest.scala
- version.sbt
Engine2's have been tested in production @ Coursera, and
they seem to be behaving. Therefore, we're going to roll
forward and use Engine2's by default. (You can roll back
by importing the old PlayJson engines.)
> Use Engine2's by default.

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NonNestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/router2/PlayNaptimeRouterIntegrationTest.scala
- naptime/src/main/scala/org/coursera/naptime/actions/NaptimeActionSerializer.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/test/scala/org/coursera/naptime/access/HeaderAccessControlCombinersTest.scala
- naptime/src/test/scala/org/coursera/naptime/router2/NestingCollectionResourceRouterTest.scala
Previously Engine2's required that the response object in actions be
serializable to a `DataMap`. This is too restrictive, because actions
are the escape hatches from the Naptime system, and must thus support
responses of strings, `JsValues`, and other primitive types. We thus
define a new type that is more general and more flexible to support
actions.
> Relax type restrictions for actions.

- naptime/src/main/scala/org/coursera/naptime/errors.scala
Add a 502 error (bad gateway) as standard naptime error option.
Also fix an incorrect comment.
@josh-newman @saeta
> Add bad gateway as error option

- naptime/src/test/scala/org/coursera/naptime/actions/RestActionCategoryEngine2Test.scala
- naptime/src/test/scala/org/coursera/naptime/actions/util/Validators.scala
Test the engine2 implementations to ensure they perform correctly
in the presence of If-None-Match headers and correctly return
HTTP 304 NOT MODIFIED responses with empty bodies.
> Add If-None-Match tests for Engine2's

- naptime/build.sbt
- naptime/src/main/scala/org/coursera/naptime/ari/graphql/GraphQL.scala
- naptime/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala
- naptime/src/main/scala/org/coursera/naptime/ari/graphql/graphqlParser.scala
- naptime/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParserTest.scala
- project/NamedDependencies.scala
- Adds sangria dependency to Naptime
- Adds a GraphQL Parser object that can parse a GraphQL String into a Naptime Request object
- Recursively parses fields into Naptime RequestFields
- Adds unit tests for parsing
Still a few TODOs left around error handling and argument parsing (GraphQL AST types into JSON)
PTAL @saeta
> Add initial GraphQL parsing library

- naptime/src/main/scala/org/coursera/naptime/actions/NaptimeActionSerializer.scala
We can support serializing any object that defines a Play-JSON Writes.
> Generalize Naptime Action Serializer's Play-JSON

- naptime-testing/src/test/pegasus/org/coursera/naptime/Course.courier
- naptime-testing/src/test/pegasus/org/coursera/naptime/Instructor.courier
- naptime-testing/src/test/pegasus/org/coursera/naptime/InstructorId.courier
- naptime-testing/src/test/pegasus/org/coursera/naptime/couriertests/ExpectedMergedCourse.courier
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime/src/main/scala/org/coursera/naptime/Types.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/main/scala/org/coursera/naptime/resources/resources.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
- naptime/src/main/scala/org/coursera/naptime/router2/ResourceRouter.scala
- naptime/src/test/scala/org/coursera/naptime/TypesTest.scala
Summary:
In order to build the automatic resource inclusion engine, to support
GraphQL, and add links to the documentation between related resources,
we need to incorporate the related fields information into the "merged"
type schema.
Because the Engine, GraphQL and others are centered around Courier and
Pegasus schemas, I've begun constructing a set of classes that can form
the basis for a more integration-style test suite in the
`NestedMacroCourierTests` class. The first test in this class is a test
of the related fields information functionality added in this commit.
Because we are centering upon courier models, I've added a couple extra
abstract classes that reduce the amount of boilerplate required for
resources using courier types.
> Incorporate related resource information in schema

- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
The engine must also expose the set of types that make up the
collection of resources to the presentation layer.
> Add data schemas to ari API.

- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/MergedCourse.courier
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- naptime/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilderTest.scala
Set up the basic infrastructure for testing the engine implementation.
Currently, we only have a trivial engine implementation that cannot
handle any automatic joining.
> ARI: Initial Engine Impl Tests

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestAction.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/fetcher/LocalFetcher.scala
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/ResponseTest.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
This commit implements the long term response model, as per the design
discussions. It converts all ARI-related code to use it, and adds a
number of tests to ensure correctness.
Additionally, thanks to the new response model, we are able to implement
a more sophisticated handling of multiple top-level requests in the
engine.
> Design response model + EngineImpl improvements

- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
This commit adds support for a single level of automated nested/joining
of related resources. Subsequent commits will add support for more
foreign-key types of joins, as well as support alternate joins such
as reverse includes / etc.
Additionally, this commit cleans up the engine API. There were unused
components of the engine API that won't be used. By removing the
unnecessary additional fields in the engine API, we avoid tangling the
code and subsequent developer confusion.
> Support basic joins.

- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/Coordinates.courier
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/MergedCourse.courier
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/MergedPartner.courier
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/PartnerId.courier
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- naptime/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilderTest.scala
In this commit, we add support for joining against single foreign key
fields.
Additionally, we add a test to ensure that complex fields do not cause
the engine trouble.
> Support single element joins.

- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
The latest version of naptime causes the following error when compiling:
```
[error] /Users/bryan/base/coursera/infra-services/services/rapidash/app/org/coursera/rapidash/RapidashModule.scala:40: not found: value Keyed
[error]     bindResource[AppResource]
```
Using the full reference to `Keyed` should resolve this.
PTAL @saeta . cc @yifan-coursera
> Use fully-qualified reference to Keyed

- naptime/src/main/scala/org/coursera/naptime/router2/NaptimePlayRouter.scala
- naptime/src/test/scala/org/coursera/naptime/router2/NaptimePlayRouterTest.scala
Computing the full path is required to display the correct documentation.
In order to handle nested resources correctly, we need to stop recursing
when we hit the root resource. This commit fixes that.
> Fix computing full path.

- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/MergedInstructor.courier
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
If Resource A points to Resource B, and Resource B points to Resource C
a single query should be able to link everything up. This commit extends
our engine from supporting only a single hop, to supporting multiple
hops.
> Support arbitrary recursive nesting of resources.

- naptime/src/main/scala/org/coursera/naptime/Types.scala
- version.sbt
To support an incremental upgrade from Naptime 0.2.3 to 0.2.4+, add this
extra method to support the old behavior.
> Maintain the old Types.computeAsymType ABI

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/ArbitraryRecord.courier
- naptime/src/main/pegasus/org/coursera/naptime/schema/ArbitraryValue.courier
- naptime/src/main/pegasus/org/coursera/naptime/schema/Parameter.courier
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
This augments the "default" value for parameters in a REST action to include additional information about types. Currently, the default value is just the string representation of the value. However, because external clients don't have information about the resource schema, its impossible to know what type the default value is.
By using a Courier union type, we can include "metadata" about the default value's type, which can then be parsed by other servers more easily.
PTAL @saeta and @yifan-coursera
> Convert naptime defaults to use ArbitraryValue courier type

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- version.sbt
This handles two different cases, and fixes schema generation:
- Field definitions that are `NullType`
- Field definitions that contain recursive references
PTAL @saeta
> Handle recursive model definitions and null field definitions

- naptime-testing/src/test/scala/org/coursera/naptime/IdInferenceMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
It is quite common to use a more sophisticated key type. Often, these key types
have a single apply method in the companion object that corresopnds to the
fields of the serialized form of the type. This commit extends the macro to
automatically infer the schema for these more sophisticated key types.
Additionally, we capture the changes in some unit tests to verify the correct
operation of the macro.
> Infer additional key type schemas

- naptime/src/main/scala/org/coursera/naptime/Types.scala
- naptime/src/test/pegasus/org/coursera/naptime/IdWithIdField.courier
- naptime/src/test/scala/org/coursera/naptime/TypesTest.scala
- version.sbt
In some cases, a key courier type might define its own id field (e.g.
only a single part of the key is required to uniquely identify the
record). This commit makes the Types computation a little bit smarter.
Note that relying on this behavior is a potential code smell.
> Handle Key types that define their own id field

- naptime/src/main/scala/org/coursera/naptime/ari/LocalSchemaProvider.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- version.sbt
Previously, the EngineImpl directly pulled from the local naptime resources.
However, this does not work in distributed mode. Instead, we must add a layer
of indirection to allow for custom distributed / remote SchemaProviders.
> Abstract NaptimeRoutes behind SchemaProvider trait.

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilderTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/MergedCourse.courier
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
List types weren't being parsed correctly (due to the missing `.asScala`), causing a parsing exception and the entire query for any field that was a list to fail. This fixes that issue, and adds a simple test.
PTAL @saeta
> Fix parsing of complex child types in lists

- examples/src/main/pegasus/org/coursera/example/Course.courier
- examples/src/main/pegasus/org/coursera/example/Instructor.courier
- examples/src/main/resources/routes
- examples/src/main/scala/resources/CoursesResource.scala
- examples/src/main/scala/resources/InstructorsResource.scala
- examples/src/main/scala/stores/CourseStore.scala
- examples/src/main/scala/stores/PartnerStore.scala
- naptime-graphql/build.sbt
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphqlSchemaProvider.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlContext.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/DefaultGraphqlSchemaProviderTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilderTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime/src/main/scala/org/coursera/naptime/ari/LocalSchemaProvider.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- project/NamedDependencies.scala
- version.sbt
- Adds connection and edge / node support to schemas
- Update resolvers to parse through edges + nodes
- Modify SangriaGraphQlContext to take in a full response object
- Use response information when pulling lists of models from a request
- Completely omit resources from a schema that don’t have valid handlers or models
- Reduce many errors to warnings
- Fix a couple of problems with the example app
- Bump version number
PTAL @saeta
> Add relay schema support

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParserTest.scala
- version.sbt
- Fragments on top-level resources weren’t being parsed correctly. Now they are
- global id generation for non-string ids was also broken. now its fixed
PTAL @saeta
> Fix fragment parsing and __id generation

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- version.sbt
This moves alias matching from the resource itself to the selection in the resource, so data can now actually be returned.
Wrote a unit test to verify that this works (and before the change, the unit test fails)
PTAL @saeta
> Fix bug with aliases on top-level resources

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParserTest.scala
- version.sbt
Finders require an extra `?q=finderName` argument in their requests to specify the correct endpoint. This commit adds that argument in the parsing layer so both the RemoteFetcher and LocalFetcher can make the finder requests properly.
PTAL @saeta . I'm still unsure whether this logic should live in the parser or in the fetchers. I opted to put this in the parser only to avoid having to duplicate the logic across the RemoteFetcher and LocalFetcher (which right now live in two separate codebases). Open to other suggestions though...
> Add a `q={finderName}` argument to parsed top-level resources

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParserTest.scala
- version.sbt
This modifies all `get` top-level requests to instead be multigets. This allows us to remove a special case from our url construction libraries, and also fixes a bug where finders that have an `id` argument were being parsed as gets instead.
PTAL @saeta 
cc @lewisf
> Parse all `get` lookups as multigets

- examples/build.sbt
- examples/src/main/pegasus/org/coursera/example/AnyData.courier
- examples/src/main/pegasus/org/coursera/example/Course.courier
- examples/src/main/scala/stores/CourseStore.scala
- naptime-graphql/build.sbt
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/marshaller/NaptimeMarshaller.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/types/NaptimeTypes.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/DefaultGraphqlSchemaProviderTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilderTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/AnyData.courier
- naptime/src/test/pegasus/org/coursera/naptime/ari/graphql/models/MergedCourse.courier
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- project/NamedDependencies.scala
- version.sbt
Some of our Courier models support a `passthroughExempt` flag, which lets the model support an arbitrary, untyped DataMap as a field. GraphQL/Sangria was freaking out when seeing this though, as there were no fields defined (which is not allowed according to GraphQL’s spec). This takes a lot of inspiration from both https://github.com/taion/graphql-type-json and https://gist.github.com/OlegIlyenko/5b96f4b54f656aac226d3c4bc33fd2a6 to add a `DataMapType` to the GraphQL schema we support.
TODO: add tests for this :). But initial thoughts would be nice, in case I have to end up refactoring any of this.
PTAL @saeta , and cc @lewisf as you need this for Nostos support to work properly.
> Add DataMap support to JSON serializer and schemas

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionCategoryEngine2.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/test/pegasus/org/coursera/naptime/ari/ResponseTest.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
Adds a pagination model to the TopLevelResponse, allowing us to pass pagination data from a response throughout the parsing and serialization flows.
PTAL @saeta
> Add ResponsePagination model to TopLevelResponse

- examples/src/main/scala/ResourceModule.scala
- examples/src/main/scala/resources/CoursesResource.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NaptimeModuleTest.scala
- naptime/src/main/scala/org/coursera/naptime/NaptimeModule.scala
- naptime/src/main/scala/org/coursera/naptime/router2/NaptimePlayRouter.scala
- naptime/src/main/scala/org/coursera/naptime/utilities.scala
When computing schemas for resources, if the types are neither
courier-based nor primitives, a reflection-based schema-inference
algorithm is run. This works fine for case-classes, but fails miserably
on some of their fields (e.g. if a field is a java.util.Date). This
results in relatively useless schemas (e.g. for GraphQL).
In this commit, I have added a Guice Multi-binding/MapBinding-based
implementation to register these overrides. Additionally, I've added a
utility that can fix up these inferred schemas at runtime based on the
configured overrides. Finally, I've added a test that verifies the
correctness of all of the above.
> Add schema inference override registry.

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/exceptions.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/PrimitiveFieldTest.scala
Courier serializes Ints and Longs in the same format over the wire. When we parse the results into DataMaps, some Longs can be parsed and stored as Ints, which then leads to CastClassExceptions when trying to read the value as a Long. This change uses the expected DataSchema type and the “validate” method on DataMaps to correctly parse the value into the proper format.
PTAL @saeta
> Properly “fix-up” data being parsed into DataMaps

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/exceptions.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/models.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationFieldTest.scala
- version.sbt
Also pulls ParentContext out to its own file just to make things nicer, and creates a new exception class to use.
PTAL @saeta
> Set `gets` as nullable to handle 404s

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/models.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceFieldTest.scala
Basic approach is that each field selection counts as 1, remote `get` requests count as 10, and paginated remote requests count as 10 * (limit / 10). I imagine we’ll be tweaking this _a lot_ as we go, but this will at least prevent against a lot of basic attacks possible on the graphql endpoint.
Thoughts, @saeta ? and maybe @jnwng and @lewisf have thoughts too
> Adds a naive approach to calculating complexity

- examples/src/main/resources/logback.xml
- examples/src/main/scala/ResourceModule.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphQLController.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineMetricsCollector.scala
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- provides a trait that can be overridden by clients to collect and report metrics from the engine into a downstream system (i.e. DataDog)
- Returns the number of downstream requests from the engine as a response header on GraphQL requests (for developer debugging purposes)
@saeta -- thoughts on this approach? I'm working on tests for this now, but want to get your opinion on things before I spend too much time on tests (in case I have to redo some of this)
> Add engine metrics collector to the Engine

- naptime/src/main/scala/org/coursera/naptime/utilities.scala
- naptime/src/test/pegasus/org/coursera/naptime/RecursiveChild.courier
- naptime/src/test/pegasus/org/coursera/naptime/RecursiveModelBase.courier
- naptime/src/test/scala/org/coursera/naptime/SchemaUtilsTest.scala
- version.sbt
The schema fixup helper recursively traverses through recorddataschemas. However, some schemas are recursive, which would lead to a StackOverthrowException here. To fix it, we’ll keep track of the nodes that we’ve visited to ensure that we don’t get stuck in a loop
PTAL @saeta or @yifan-coursera
> Support recursive models in fixupInferredSchemas

- naptime-testing/src/test/scala/org/coursera/naptime/IdInferenceMacroTests.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
There are some key types that are non-courier’d that can’t have their types inferred through reflection. This can occur when the type is or includes a Java class inside of it (i.e. java.util.UUID). In these cases, we can assume that there is a StringKeyFormat available to convert the key type to a string, so it is safe to assume that the ID in the response will be of type string.
In these cases, when the key type cannot be inferred, it will fall back to a string. By falling back, we can ensure that the merged type can be generated correctly, and add graphql support to these resources.
PTAL @saeta and @yifan-coursera
> Default the type for a key field to string

- naptime/src/main/scala/org/coursera/naptime/utilities.scala
- naptime/src/test/pegasus/org/coursera/naptime/NestedChild.courier
- naptime/src/test/pegasus/org/coursera/naptime/RecursiveModelBase.courier
- naptime/src/test/pegasus/org/coursera/naptime/StringLikeField.courier
- naptime/src/test/scala/org/coursera/naptime/SchemaUtilsTest.scala
DataSchema overrides only worked for fields in a recorddataschema, but there were some cases where we need to fix up a schema that's a member in a list or map. This now looks at the item types for those, and fixes them up.
PTAL @yifan-coursera
cc @saeta
> Support overrides dataschemas in arrays and maps

- examples/src/main/resources/routes
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/EngineMetricsFilter.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilter.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/models.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/controllers/filters/FilterTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilterTest.scala
- version.sbt
Note: this changes the way that the filters work to instead pass around JsObjects instead of a response. This means that filters / the GraphQL engine cannot alter the response at all (including response codes + headers), but instead must put all data on the response body and _always_ return a 200 access code. This is acceptable with the way that GraphQL works, but is a change to keep in mind
PTAL @yifan-coursera and cc @jnwng
> Support query batching in the naptime controller

- examples/src/main/scala/ResourceModule.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilter.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilterTest.scala
We were hitting the limits of the complexity filter with some normal queries, so this pulls the max complexity score out to a config that we can override. This is still a somewhat naive approach, but we can modify it more later on once we better understand what we need.
We also have metrics / monitoring on the number of downstream requests we make, so we'll keep a close eye on that and make sure it doesn't go too crazy.
PTAL @yifan-coursera
> Allow overriding of max complexity score

- examples/src/main/pegasus/org/coursera/example/Course.courier
- examples/src/main/pegasus/org/coursera/example/CourseMetadata.courier
- examples/src/main/pegasus/org/coursera/example/Instructor.courier
- examples/src/main/scala/resources/CoursesResource.scala
- examples/src/main/scala/resources/InstructorsResource.scala
- examples/src/main/scala/stores/CourseStore.scala
- examples/src/main/scala/stores/InstructorStore.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParser.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlParserTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/models.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceFieldTest.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/ReverseRelationAnnotation.courier
- naptime/src/main/scala/org/coursera/naptime/Types.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineHelpers.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/test/scala/org/coursera/naptime/ari/engine/EngineImplTest.scala
- version.sbt
While forward relations are very useful in a majority of cases (i.e. courses -> instructors, where the course model has an instructorId on it), there are some cases where a relation is necessary where the first model doesn't have any reference to the second. For instance, while a Membership model has a CourseId available on it, the Course model has no reference to all of the memberships available.
In order to create this course -> membership relationship though, we can dynamically fetch the relationship via a query to the membership resource, which, given information about the course, can return a list of memberships + ids for the relationship. This is referred to as a "reverse relationship", where the relationship data is stored on the related model.
These relationships are defined in …
> Add support for reverse relations to the ARI engine

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumField.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumFieldTest.scala
GraphiQL doesn’t like when there’s an enum defined without any member values. However, that is valid syntax in Courier. In order to handle this case and prevent graphiql from breaking in the future, we’ll simply add an “$UNKNOWN” member value to all empty enums.
PTAL @jnwng and @yifan-coursera
> Add a placeholder value for empty enums to support GraphQL syntax

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumField.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeEnumFieldTest.scala
- version.sbt
cc @yifan-coursera and @jnwng:
```Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "$UNKNOWN" does not.```
> Fix enum fallback

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationFieldTest.scala
- version.sbt
When the id field is a non-string value, pagination using `start` was broken because it was comparing an int and start value. This just calls toString on the id value to always compare strings
PTAL @jnwng / cc @yifan-coursera
> Fix `start` pagination for non-string fields (i.e. ints)

- naptime/src/main/scala/org/coursera/naptime/models.scala
Adds the model to support multiget reverse relations. Note: the engineimpl / schema builder already supported multigets... this was the only thing missing
PTAL @jnwng / cc @yifan-coursera
> Add model for multiget reverse relation

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/SchemaMetadata.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceFieldTest.scala
Some resources manually construct a related resource to append extra data. However, these related resources don’t actually exist, which was causing the schema builder to break.
This changes things to optionally fall back to the original field type if the resource doesn’t exist
PTAL @jnwng / cc @yifan-coursera
> Handle fake related resources

- examples/src/main/scala/ResourceModule.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQlControllerMetricsCollector.scala
- version.sbt
This adds a metrics collector that will collect timing data from the GraphQL controller. In Naptime, a logging collector is used to send the metrics as log statements. However, in other codebases, the data can be sent to a third party collector (i.e. Datadog).
This also makes a small change to better parallelize the GraphQL Batch endpoint (previously, query parsing was all done in serial)
PTAL @yifan-coursera and @jnwng
> Add a metrics collector to pull execution time + parallelize batching

- examples/src/main/pegasus/org/coursera/example/CourseMetadata.courier
- examples/src/main/pegasus/org/coursera/example/InstructorId.courier
- examples/src/main/pegasus/org/coursera/example/Partner.courier
- examples/src/main/scala/resources/CoursesResource.scala
- examples/src/main/scala/resources/InstructorsResource.scala
- examples/src/main/scala/resources/PartnersResource.scala
- examples/src/main/scala/stores/CourseStore.scala
- examples/src/main/scala/stores/InstructorStore.scala
- examples/src/main/scala/stores/PartnerStore.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-testing/src/test/pegasus/org/coursera/naptime/Course.courier
- naptime-testing/src/test/pegasus/org/coursera/naptime/couriertests/ExpectedMergedCourse.courier
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime/src/main/scala/org/coursera/naptime/Types.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineHelpers.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- naptime/src/main/scala/org/coursera/naptime/ari/fetcher/LocalFetcher.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- version.sbt
This change allows a relation (either forward or reverse), defined on the `Fields` object in a resource, to reference deeply nested records and unions.
For example, if a Course model has a union of Instructors and TeachingAssistants, a related resource can be added to the Instructor model through the union.
This also changes the variable interpolation to support referencing these nested models too.
PTAL @yifan-coursera and cc @jnwng
> Support defining relations on nested models / unions

- examples/src/main/scala/resources/CoursesResource.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- version.sbt
Previously we were only comparing resource name and alias when fetching top-level ids. However, if you have a CoursesV1Resource with a nested multiGet and getAll, the ids of the first would be used for all responses.
> Compare both alias and name when pulling top-level data

- examples/src/main/pegasus/org/coursera/example/Partner.courier
- examples/src/main/scala/resources/PartnersResource.scala
- examples/src/main/scala/stores/PartnerStore.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilter.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineHelpers.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- version.sbt
When lists were stringified and combined for reverse relations, we could end up with a query parameter that looks like `”,idTwo”` in cases where one element’s list of ids was empty. This causes the request to be invalid, and for data to not be returned.
This fix simply filters out empty strings, to ensure that all ids are valid when stringifying the args.
> Better handle reverse relations on empty lists

- naptime-models/src/main/scala/org/coursera/naptime/courier/SchemaInference.scala
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestUnion.courier
- naptime-models/src/test/scala/org/coursera/naptime/courier/SchemaInferenceTest.scala
- version.sbt
In some cases, we have a scala case class that has a nested Courier record / union as a field inside of it. Currently, when we try to infer the schema, we'll come across the nested union schema, and mark it as "unable to be inferred". However, we _have_ the schema available at that point, we're just not using it.
This change checks every class we try to infer (including nested classes inside a case class) and check if it's a pegasus schema. If it is, we pull the known schema from that, and ignore all attempted inferred schemas.
cc @saeta
> Use pegasus schemas for nested courier models inside case classes

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala
In the `read` provided by `recordTemplateStringKeyFormat`, if the tuple [here](https://github.com/kyewei/naptime/blob/cb5290356348a1fba99cd850415047298c66698f/naptime-models/src/main/scala/org/coursera/naptime/courier/StringKeyCodec.scala#L198) fails the check, the error leaks out and a `None` is not returned. Similarly, if a validation in `validateAndFixUp()` fails, the exceptions escapes as well.
Changes: Wrapped lines in try-catch and added tests.
@yifan-coursera
> Fix escaping exceptions in StringKey parsing

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationField.scala
- version.sbt
DataMap’s `getDataList` field can return a null value. However, we were immediately calling `.asScala` on a lot of these values, which would obviously break. To fix this, we wrap the possibly-null value in an `Option` and then handle that safely (by either falling back to an empty list or calling getOrElse(null) after only calling asScala on the unwrapped value.
> Make nullable field retrieval safer

- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- version.sbt
If a field isn’t set, that may mean its a nullable field. In that case, we should just fall back to an empty string, so we remove it when making a subsequent multiget.
> Don’t fall back to field name if a reverse relation field isn’t set

- examples/src/main/scala/resources/CoursesResource.scala
- naptime-testing/src/test/pegasus/org/coursera/naptime/couriertests/ExpectedMergedCourse.courier
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/ReverseRelationAnnotation.courier
- naptime/src/main/scala/org/coursera/naptime/Types.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- version.sbt
This lets us write documentation describing the "edge" field that is auto-created by a reverse relation. For instance, if we add a new PrimaryPartners field on a Course that is populated by some arbitrary finder, we can describe on the field what that relationship means.
> Allow setting docs on reverse-relation fields

- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- version.sbt
When fetching relations on a multiget, we batch requests together to be as optimal as possible. However, we keep all query parameters from the original requests on the merged requests, including pagination-affecting parameters (i.e. `start` and `limit`). This can cause a problem, because if we wanted to limit the first 3 results from each multiget, that’ll cause us to fetch only 3 results total from all of the merged requests.
It's safe to remove these parameters from the underlying request, because each multiget relation handles its own pagination based on the source list of ids, so requesting a limit of 3 will still result in 3 elements in the response.
> Remove pagination query params from multiget relations

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/models.scala
- naptime-models/src/main/scala/org/coursera/naptime/courier/SchemaInference.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/Parameter.courier
- naptime/src/main/pegasus/org/coursera/naptime/schema/ParameterDataSchema.courier
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
- naptime/src/test/scala/org/coursera/naptime/actions/RecordTemplateNaptimeSerializerTest.scala
- version.sbt
This change adds a new `typeSchema` field to the Parameter, which contains a DataSchema (serialized as a DataMap) that defines the parameter type. This allows the type of a parameter to be serialized in a better way than a string, so it can be parsed by the GraphQL assembler and used in schema generation. (Presently, the scala typename is being parsed with a regex, but that’s terrible)
Once this is landed, the schema store will be updated to parse the correct parameter types, and then the GraphQL schema builder can use that type to generate the graphql parameters.
PTAL @saeta and @yifan-coursera
> Add DataSchemas for parameter types on naptime handlers

- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
Use the explicit collection.JavaConverters instead of implicit conversions in collection.JavaConversions.
JavaConversions is deprecated in 2.12. And due to the macro impl, this breaks linter we plan to add into infra-services.
http://www.scala-lang.org/api/2.12.x/scala/collection/JavaConversions$.html
> Use asScala explicitly in MacroImpl

- examples/src/main/scala/stores/CourseStore.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilter.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationField.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/Parameter.courier
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineImpl.scala
- Null values for arguments are allowed in graphql, but when sent in REST, they should be omitted completely.
- We're reporting errors under an unnecessary level -- this moves errors up to top level to allow to be parsed by apollo and graphiql better
> Fix null query parameters and error response format

- examples/src/main/pegasus/org/coursera/example/CertificateCourseMetadata.courier
- examples/src/main/pegasus/org/coursera/example/Course.courier
- examples/src/main/pegasus/org/coursera/example/CourseMetadata.courier
- examples/src/main/pegasus/org/coursera/example/DegreeCourseMetadata.courier
- examples/src/main/scala/resources/CoursesResource.scala
- examples/src/main/scala/stores/CourseStore.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionField.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionFieldTest.scala
- version.sbt
Many of our Courier unions use `typedDefinitions`, which allows providing a “friendly name” to a union type, instead of using the fully qualified name.
This change adds supports for these typedDefinitions to Courier, both by changing the name of the member key in the union type, as well as parsing the typedDefinition response correctly.
PTAL @yifan-coursera / cc @qtran-coursera
> Support typedDefinitions in unions

- README.md
- naptime/src/main/scala/org/coursera/naptime/router2/NaptimePlayRouter.scala
- naptime/src/test/scala/org/coursera/naptime/router2/NaptimePlayRouterTest.scala
Make resources that descend from RootResource print routes in the standard `$name.v$version` format. This is currently causing routes to be mis-printed for resources that subclass `CourierCollectionResource`, and causing our internal tests to fail cc @pseudonom .
> Fix route path statements

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/EngineHelpers.scala
- version.sbt
When we fetch data for related resources, we must insert it in the datamap based on the alias key, not the field name. This allows us to fetch multiple related resources with different parameters, without overwriting the data based on the original field name
PTAL @yifan-coursera @vkuo-coursera
> Respect alias names for related resources

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphqlSchemaProvider.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeRecordField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceUtils.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeTopLevelResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/SchemaErrors.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/SchemaMetadata.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlSchemaExecutionTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/controllers/filters/FilterTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginationFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeTopLevelResourceFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionFieldTest.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- version.sbt
**This is a pretty large refactor that does the following:**
- Instead of simply logging errors (or throwing exceptions that can be caught later on), most methods were refactored to return SchemaErrors when applicable. There are two ways that this is done:
- Some methods return a type wrapped with `WithSchemaErrors[T]`, which converts that type into a case class that also includes a list of SchemaErrors generated during the invocation of that call. There are many instances where we want to return some value _and_ a list of errors generated along the way.
- For cases where its either Error or Value, these have been transformed to use `Either`s instead. Most of these expressions could be represented by an `Either[SchemaError, T]` rather than an `Option[T]`.
- Change resourceNames to be …
> Refactor GraphQL schema building to capture errors

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime/src/main/scala/org/coursera/naptime/ari/engine/Utilities.scala
- version.sbt
When requesting a multiget with an empty list, the generated url was invalid, and caused no requests to be returned.
This fix removes empty parameters, and also short-circuits forward relations when there are no ids available.
> Fix requests with empty multiget lists

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- version.sbt
There's currently a bug where if the id is an empty string / null, the forward relation will omit the "ids" parameter on the request, and end up requesting a getAll. Instead, if we see that we're making a forward relation and there's no id set, we should immediately just return null.
> If no id is set for a forward relation, immediately mark as null

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionField.scala
- version.sbt
This commit fixes two issues:
- First, a case when the union object itself is null, we'd throw a NPE while parsing to get the type of the union. Now we handle that case better.
- There seems to be a weird interaction when handling some DeferredActions and regular Actions in sangria, leading to confusion. This makes the types more explicit to avoid errors
> Fix null ResponsePagination objects and unions

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/SangriaGraphQlContext.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/QueryComplexityFilter.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/filters/models.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/middleware/UrlLoggingMiddleware.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/controllers/filters/FilterTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/middleware/UrlLoggingMiddlewareTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/PrimitiveFieldTest.scala
- version.sbt
Add `debugMode` flag and only send sourceUrls if in debug mode …We're currently sending the `sourceUrl` extension on every response. However, this ends up being a very large response that is for debugging purposes only.  This change adds a `debugMode` to the context, and we'll only send the sourceUrl data if the debug mode is enabled (it's disabled by default). Filters will be able to modify this flag, to allow for custom headers / authorization checking to enable debug mode.
> 	Add `debugMode` flag and only send sourceUrls if in debug mode

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- version.sbt
This fixes a regression where having a `null` in the JSON for an optional record causes a parse error.
> CourierFormats: allow JsNull values to be used for optional records

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/middleware/MetricsCollectionMiddleware.scala
- version.sbt
This will let us see if there are random slowdowns in query parsing. If not, we'll instrument more!
PTAL @yifan-coursera or @mkovacs-coursera
> Add timing for query parsing to GraphQLController

- project/NaptimeBuild.scala
`naptime-pegasus` should not depend on Scala Play because it is a pure Java project. In particular, this was adding dependencies on Scala 2.11 packages, which prevented it from being used in a project with any other Scala version.
> Remove unused Play dependency

- naptime-testing/src/test/scala/org/coursera/naptime/NaptimeModuleTest.scala
- naptime/src/main/scala/org/coursera/naptime/NaptimeModule.scala
Resource classes are dynamically injected via `Injector.getInstance` calls in `org.coursera.naptime.router2.Router`. This means that the injector does no know about the existence of resource classes and cannot eagerly instantiate singletons when running in production. This change uses `AbstractModule.getBinding` to inform Guice that the resource class binding is required, which allows Guice to eagerly instantiate singletons when running in production
> Require bindings for Resource types

- build.sbt
Use Scala 2.12.4 instead of Scala 2.11.11 by default.
> Use Scala 2.12 by default

- naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/build.sbt
- naptime-sbt-plugin/src/sbt-test/sbt-naptime/simple/project/plugins.sbt
- project/NamedDependencies.scala
- project/NaptimeBuild.scala
- project/plugins.sbt
Bump version number of courscala, courier, joda-convert, and joda-time dependencies.
> Bump dependency versions

- naptime-graphql/build.sbt
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/GraphqlSchemaProvider.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/middleware/MetricsCollectionMiddleware.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/middleware/ResponseMetadataMiddleware.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/middleware/SlowLogMiddleware.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/types/NaptimeTypes.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/DefaultGraphqlSchemaProviderTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/middleware/UrlLoggingMiddlewareTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeUnionFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/PrimitiveFieldTest.scala
- project/NamedDependencies.scala
- version.sbt
1. Upgrade sangria to 1.4.0 in order to sangria-slowlog
This resulted in some.. interesting findings
a. In [1.2.2](https://github.com/sangria-graphql/sangria/blob/v1.2.2/src/main/scala/sangria/schema/Schema.scala#L822), sangria had some default types in the Schema class that went away in [1.4.0](https://github.com/sangria-graphql/sangria/blob/v1.4.0/src/main/scala/sangria/schema/Schema.scala#L816)
b. In [1.2.2](https://github.com/sangria-graphql/sangria/blob/v1.2.2/src/main/scala/sangria/schema/Schema.scala#L219), the `ObjectType` constructor called `Named.checkObjFieldsFn(name, fields)` on the passed in field list. This went away in [1.4.0](https://github.com/sangria-graphql/sangria/blob/v1.4.0/src/main/scala/sangria/schema/Schema.scala#L190).
Both resulted in bizarre test failures that …
> Add sangria-slowlog middleware to allow for GraphQL slow logging

- sonatype.sbt
Tested by making sure `sonatypeList` works with this file, and does not work without.
> Add sonatype.sbt to make publishing work

- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
@yifan-coursera 
When I deliberately did a `Thread.sleep(50)` inside `LocalFetcher` the `coursesLocalFetcher_Finder` test failed, but with the `IntegrationPatience` the test did not fail, so I think it is doing as advertised.
This test looks like an integration test so I'm OK with adding the `IntegrationPatience` trait.
> Fix flaky naptime test by adding IntegrationPatience

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/resolvers/NaptimeResolver.scala
- version.sbt
This solves a bug where the resolver fails to properly de-duplicate multiGet ids when combining multiGets from multiple child related elements.
Instead of breaking multiGet ids strings into their constituent ids and de-duplicating the individual ids, it was de-duplicating the entire multiget ids strings for all requests.
so for this request:
```
[
{teamId: 1, memberIds: [1,2,3]},
{teamId: 2, memberIds: [1,2,3]},
{teamId: 3, memberIds: [2,3,4]}
]
```
it would have made these requests
```
members.v1?ids=1,2,3
members.v1?ids=1,2,3
members.v1?ids=2,3,4
```
but the resolver attempts to combine multiple multigets into a single multiget, which in this case produces the following (which is incorrect):
```
members.v1?ids=1,2,2,3,3,4
```
To it’s credit, the backend only return individual member …
> Deduplicate MultiGet Ids

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/resolvers/NaptimeResolver.scala
- version.sbt
- After merging a recent fix that de-duplicated ids we found that related resource `elementIds` and `elements` arrays were being re-ordered in a non-deterministic way during every request. In particular our moduleIds were being re-ordered and the order has actual meaning. 
- It turns out that the previous de-duplication fix had introduced sets and hence this non-determinism. I’ve replaced the Set introduced in parseIds with a Seq and this has corrected the problem.
- I tested using prod-preview and now the problem has gone away.
> Fix Re-ordering of Related Resource Ids

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- version.sbt
Fairly self explanatory.
Looking at this search: https://service.sumologic.com/ui/bento.html#/search/e9Lw847lmxaCfsmyKMz5FgnsNi8APIniDhOJu3gP
more than half of all of our slow queries come from calling our `onDemandSpecializations.v1` GETALL, which is because the FE passes in an empty string as s12n id. Ideally the FE doesn't do this but to protect ourselves I think it's a good idea to never call a `getAll` from a `get` request.
For actual `getAll`s, we use `NaptimePaginatedResourceField` so there's no conflict here.
> Do not attempt to fetch GetAlls accidently by adding logic to not grab results when no id value is given

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/resolvers/NaptimeResolver.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceField.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceField.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroCourierTests.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/AuthOverride.courier
- naptime/src/main/pegasus/org/coursera/naptime/schema/ReverseRelationAnnotation.courier
- naptime/src/main/scala/org/coursera/naptime/ari/models.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- version.sbt
- This change allows API developers to create related resources that are fetched with “internal” auths. 
- This is done by adding an authOverride value to the reverse relation definition on the primary resource. This will show up in the naptime resource schema and will be interpreted by assembler in order to request with the proper auth request headers.
- The purpose of this is to give developers the option to do authentication in only one place, the entry/parent resource, and use internal auth for all the related/child resources. This allows the child resources to be a bit more re-usable in that they can be attached to multiple parent resources that may all have different auth schemes.
> Introduce Related Resource Auth Override

- project/NaptimeBuild.scala
- version.sbt
By default, Play includes AkkaHttp in its dependencies along w/ its jar. This can be inconvenient for switching to Netty since Play will override any choices based on whether or not AkkaHttp exists in the classpath.
Read more:
https://www.playframework.com/documentation/2.6.x/NettyServer
> Remove AkkaHttp from dependencies

- naptime-testing/src/main/scala/org/coursera/naptime/actions/RestActionTester.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
Years ago, it was common practice to write resource-level unit tests for Coursera APIs - there are 555 usages of the existing `testAction` method in our codebase. As authorization logic became more complicated, teams increasingly moved away from resource testing because it was cumbersome to mock or fake auths. 
The irony here is that `testAction` itself requires the caller define a RestContext with authorization data, and tests only execute the authorizer's test-only `check` method. Needing to define a fully functional authorizer for testing is silly, because the bulk of its machinery won't even be exercised within a `testAction` execution. 
This revision adds a new test method that skips the `check` step of `testAction`. This makes it possible to construct test resources with trivial …
> Add testActionPassAuth to facilitate testing with trivial auth mocks

- naptime-testing/src/main/scala/org/coursera/naptime/actions/RestActionTester.scala
- naptime-testing/src/test/scala/org/coursera/naptime/AuthBuilderTest.scala
- naptime/src/main/scala/org/coursera/naptime/access/HeaderAccessControl.scala
- naptime/src/main/scala/org/coursera/naptime/actions/DefinedBodyTypeRestActionBuilder.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestAction.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionBodyBuilder.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionBuilder.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionBuilderTerminators.scala
- naptime/src/main/scala/org/coursera/naptime/actions/package.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
- version.sbt
Coursera authorization rules are often context-dependent. For example, only university staff can create and modify courses for a particular university. When this context is present as a rest handler method argument (e.g. `get(id: CourseId) = Rest ...` or `update(id: CourseId) = Rest ...`), it's straightforward to define context-aware authorizers (e.g. `Rest.auth(canManageCourse(id)...`). Unfortunately, however, we frequently put necessary authorization context data into request bodies (e.g. `create() = Rest.jsonBody[Course].create { ... }`), and in these cases authorization logic must be implemented within handler bodies. 
In the Coursera code base there are 207 applications for `runAndCheck` (authorizers used outside of an `auth` block) and 307 instances of `throw Errors.Forbidden` …
> Add body-dependent authorization capability to Rest action handler

- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/DefaultGraphqlSchemaProviderTest.scala
- naptime-testing/src/test/scala/org/coursera/naptime/CustomRequestResponseMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NestedMacroTests.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NonNestedMacroTests.scala
- naptime/src/main/pegasus/org/coursera/naptime/schema/Handler.courier
- naptime/src/main/scala/org/coursera/naptime/access/HeaderAccessControl.scala
- naptime/src/main/scala/org/coursera/naptime/router2/MacroImpls.scala
- naptime/src/test/scala/org/coursera/naptime/router2/NaptimePlayRouterTest.scala
- version.sbt
A [previous PR](https://github.com/coursera/naptime/commit/b3bd4b8a38c0106df6a833f38204c0e52284063a#diff-330091af95c9f8acd5f10a962600b245R26) simplified the representation of two unused schema fields. In spite of the fact these fields were unused, changing the representation of their underlying data type (from a union record to a simple string), was a backward-incompatible change to the model's transport format, and caused issues when deployed. 
This revision renames these fields to make object serialization backward-compatible. Legacy receivers will receive empty data for legacy field names, but since legacy receivers aren't using this data in the first place, that shouldn't cause any issues.
> Rename fields that were previously of type CustomBodyType

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestPositiveIntMoreComplex.courier
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestPositiveIntPairMapRecord.courier
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestPositiveIntPairUnion.courier
- naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala
Previously, deserializing JSON to a courier model resulted in a model that would have lazily initialized fields. This means that if one of the fields was a custom Scala class with custom validation logic in the constructor or coercer, that validation logic would be ignored during deserialization time. Instead, it would run the first time the field was accessed, leading to exceptions thrown at unexpected places. This change forces materialization of the entire model during JSON deserialization time, and causes JSON deserialization to fail if an exception is thrown by the Scala constructor or coercer.
> Materialize model during JSON deserialization

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala
Log a warning instead of throwing an exception if materialization fails during JSON deserialization. Throwing an exception is a breaking change that might change application behavior e.g. causing applications to eagerly fail if they were working with partially instantiated but invalid models previously. We plan to log warnings in this version and throw exceptions in the next version, so that developers have one version to fix their applications.
> Don't throw exception if materialization fails during JSON deserialization

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- version.sbt
- also normalize `jsObjectToTypeRefUnion` to be more specific by returning a DataMap instead of AnyRef
> Allow public access to typeref union CourierFormats methods

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/FieldBuilder.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeAnyDataFieldTest.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimePaginatedResourceFieldTest.scala
- version.sbt
It appears that `AnyData` courier fields haven't been working correctly, which led to the following error: `org.coursera.naptime.ari.graphql.schema.DataMapWithParent cannot be cast to com.linkedin.data.DataMap`.
The passthrough exempt field's `resolve` parameter will now return a `DataMap` instead of a `DataMapWithParent`. As a sanity check, this is also what we do in the case of `MapDataSchema` fields—I'd expect the behavior to be the same.
cc @cliu587
> Fixing field builder for passthrough exempt fields.

- naptime/src/main/scala/org/coursera/naptime/actions/RestAction.scala
- naptime/src/main/scala/org/coursera/naptime/actions/RestActionBuilder.scala
- naptime/src/main/scala/org/coursera/naptime/errors.scala
- version.sbt
Often in errorHandlers, we catch exceptions and throw the appropriate `NaptimeActionException` to return the correct httpCode to the client. There is currently no way to specify a cause of the `NaptimeActionException` we throw which means we lose the original exception's stack trace.
This change allows you to specify a cause when creating a `NaptimeActionException` which will preserve the stack trace of the original exception and help with debugging.
> add ability to create NaptimeActionExceptions with a cause

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala
- version.sbt
This reverts commit 8ee25943f23fb3606ceeb4486763545cf4598e07.
We want to roll this out as it's the safer default. We've had the warnings run in production for a while so we know what can break with these changes. Based on recent discussions, we believe the benefits outweigh the known breakage.
Privately tracked: https://coursera.atlassian.net/browse/DRAG-91 cc @firejade
> Throw exceptions on failures during JSON deserialization

- naptime-graphql/build.sbt
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/TracerWrapper.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/helpers/ArgumentBuilder.scala
- project/NamedDependencies.scala
- version.sbt
Opentracing integration to slowlog only came with 0.1.7 which only works with Sangria 1.4.1 and greater.
I looked at the changelog (https://github.com/sangria-graphql/sangria/blob/master/CHANGELOG.md#v141-2018-05-12) and everything looks backwards compatible. There is this note: `breaking change. All additional error object fields that were provided via HandledException are now added to the extensions field` but we don't use the other `errors` fields on the client (we do use the `.message` field, which is unchanged), so this is a good thing as well as it gets us closer to graphql spec compliance. 
The integration point is a wrapper class, `TracerWrapper`, that allows the resource (assembler) to optionally provide this class as a module.
> Upgrade Sangria to 1.4.2 and slowlog to 0.1.8, add opentracing hook

- naptime-graphql/build.sbt
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/TracerWrapper.scala
- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- project/NamedDependencies.scala
- version.sbt
To support something like https://phabricator.dkandu.me/D88490 for assembler, we need to be able to inject middlewares. This change makes that behavior possible, and gets rid of the hard coded opentracing middleware.
PTAL @amory-coursera, @dguo-coursera
> Make middlewares injectable and remove hard coded opentracing integration

- naptime-testing/src/main/scala/org/coursera/naptime/actions/RestActionTester.scala
- naptime-testing/src/test/scala/org/coursera/naptime/NonNestedMacroTests.scala
- version.sbt
See contents for details. Missing type annotation caused a name conflict in existing tests.
> Minor fixes for test compatibility

- project/NaptimeBuild.scala
- project/plugins.sbt
- version.sbt
Pulls in this diff along with some other library version upgrades thats needed to avoid classpath hell in our main repo: https://github.com/playframework/playframework/issues/9612
> Bump Play to version 2.6.24

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- version.sbt
See added comment. It appears we handle this case explicitly (`jsObjectToRecord` is what is calling `jsValueToData`) so maybe this check is somewhat over-eager. 
Specifically, L544-550 of this file.
```
if (field != null) {
val result = jsValueToData(newSchemaPath, value, field.getType)
if (result != Null.getInstance) {
Some(field.getName -> result)
} else {
None
}
```
Also, note that the check is only a log and not a throw, if something terrible happens downstream, we'd still get the same error behaviors.
> Quiet noisy logs when deserializing a NULL as we appear to be handling that case explicitly

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceUtils.scala
- naptime-graphql/src/test/scala/org/coursera/naptime/ari/graphql/schema/NaptimeResourceUtilsTest.scala
- version.sbt
Should fix the issue described in https://coursera.slack.com/archives/C025SQ0GH/p1594832573018600 which comes from ids with `$` embedded. Looks like the root cause is the replacement text for the `regex. replaceAllIn` method needs to escape special characters. They provide an API for this.
Existing unit tests should cover regressions, and added a new unit test for this case.
This is only deployed through assembler so fairly safe to deploy with traffic shifting + E2E tests as well.
> Use Matcher.quoteReplacement to escape ids with special characters

- naptime/src/main/pegasus/org/coursera/naptime/schema/IncludedRelationAnnotation.courier
- naptime/src/main/pegasus/org/coursera/naptime/schema/LinkedRelationAnnotation.courier
- naptime/src/main/scala/org/coursera/naptime/Types.scala
- naptime/src/main/scala/org/coursera/naptime/models.scala
- naptime/src/test/pegasus/org/coursera/naptime/Empty.courier
- naptime/src/test/scala/org/coursera/naptime/TypesTest.scala
This PR adds Naptime include relations to the dataSchema, similar to how we stuff the GraphQL relations in as pseudo-fields. In particular, we add a new field property `"included"` with is an object with a `"resourceName"` property. When we have both a GraphQL and Naptime relation, both the `"relatedOn"` and `"included"` properties are present, otherwise only the relation that applies for that pseudo-field is present. Consider the resource with fields:
```
ResourceFields
.withRelated(
"legacyRelation" -> ResourceName("first", 1),
"modernRelation" -> ResourceName("second", 2))
.withGraphQLRelations(
"modernRelation" -> GetGraphQLRelation(ResourceName("second", 2), "relatedId"))
```
It produces a fields array on the model for this resource like this:
```
{
"fields": [
{
"name": …
```
> Add includes relations to dataSchema

- naptime-graphql/src/main/scala/org/coursera/naptime/ari/graphql/controllers/GraphQLController.scala
- version.sbt
JIRA Ticket- https://coursera.atlassian.net/browse/FCORE-562
As part of the security ticket created we want to omit extra information provided by Assembler in case of QueryAnalysisError.
> Omit query analysis error message

- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierFormats.scala
- naptime-models/src/main/scala/org/coursera/naptime/courier/CourierSerializer.scala
- naptime-models/src/main/scala/org/coursera/naptime/courier/validation/CoercionMode.scala
- naptime-models/src/main/scala/org/coursera/naptime/courier/validation/RequiredMode.scala
- naptime-models/src/main/scala/org/coursera/naptime/courier/validation/ValidateDataAgainstSchema.scala
- naptime-models/src/main/scala/org/coursera/naptime/courier/validation/ValidationOptions.scala
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestArrayOfEnum.courier
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestEnum.courier
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestRecordWithEnum.courier
- naptime-models/src/test/pegasus/org/coursera/naptime/courier/TestWrappedEnum.courier
- naptime-models/src/test/scala/org/coursera/naptime/courier/CourierFormatsTest.scala
- naptime-models/src/test/scala/org/coursera/naptime/courier/validation/ValidateDataAgainstSchemaTest.scala
- version.sbt
Duplicate of https://github.com/coursera/naptime/pull/283 with two changes:
- Updates copyright notices on copied source files.
- Applies enum relaxed validation to StringKey deserialization as well. That is, StringKeys containing unknown enums will also deserialize them to `$UNKNOWN` instead of throwing an exception.
This PR changes the validation logic used by courier to ignore unrecognized enum values instead of returning a JsError.
I copied the 3.1.1 version of [ValidateDataAgainstSchema](https://github.com/linkedin/rest.li/blob/b4e2d5669054907462ee2d9c3dc3fc13274c0b9b/data/src/main/java/com/linkedin/data/schema/validation/ValidateDataAgainstSchema.java) into the naptime repo, re-writing from java to scala. This class has a lot of options, so I removed support for options we're not …
> loosen validation to support unrecognized enum values

- version.sbt
Release 0.11.6 was accidentally compiled with Java 17 instead Java 8. Bumping version to create a new release with the right Java version.
> bump version to 0.11.7
